### ISSUE TITLE
cedar-14 support

### ISSUE THREAD

**Issue by hone** [heroku/heroku-buildpack-activestorage-preview#1]
Thanks for putting this together. I tested this against cedar-14 and it doesn't work since ubuntu 14.04 removed the `ffmpeg` package.

```
remote: -----> Installing binary dependencies for ActiveStorage Preview
remote:        Updating package list
remote:        Downloading packagesE: Package 'ffmpeg' has no installation candidate
remote:  !     Push rejected, failed to compile ActiveStorage Preview app.
remote: 
remote:  !     Push failed
```

**Comment by jbyrum** [comment]
@ojacobson @hunterloftis @hone Owen is looking into this right now

**Comment by hunterloftis** [comment]
Hey @jbyrum what ended up happening with this?

**Comment by jbyrum** [comment]
@hunterloftis Owen will have the latest.  @ojacobson Owen?

**Comment by hone** [comment]
@jbyrum @ojacobson ping?

**Comment by schneems** [comment]
I've made our documentation on this feature public. I removed references to this buildpack as it will not work with all customers and currently contains CVEs. Currently we do not have a fully supported solution for ffmpeg on the platform. Instead i'm directing people to use 3rd party solutions, which I don't know if they exist:

-  https://devcenter.heroku.com/articles/active-storage-on-heroku

I will be directing people to that article from buildpack warnings soon:

- https://github.com/heroku/heroku-buildpack-ruby/pull/739

**Comment by ojacobson** [comment]
There's a difficult wrinkle: there aren't, as far as I can find, any supported sources for ffmpeg packages on Ubuntu 14.04. Due to a fork, Ubuntu was shipping libav rather than ffmpeg at the time, and my experiments with wrapping libav's tools with ffmpeg-shaped scripts did not go brilliantly.

@hone Last I heard, you were investigating whether it's practical to ship our own debs of ffmpeg for Ubuntu 14.04, to address that gap. Is that still accurate? If so, can we draw any conclusions as to whether that's a practical way to support ActiveSupport previews on Cedar-14?

**Comment by cji** [comment]
@ojacobson this deb will install a static version of the very latest ffmpeg and its dependencies and works on 14.04 and 16.04 - https://github.com/heroku/sffmpeg/blob/master/sffmpeg_4.0_amd64.deb
